// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package realworld

import (
	"github.com/google/go-cloud/wire"
	"github.com/gorilla/mux"
	"net/http"
)

// Injectors from container.go:

func InjectHTTPServer() (HTTPServer, error) {
	logger := NewLogger()
	env, err := NewEnv()
	if err != nil {
		return HTTPServer{}, err
	}
	router := NewRouter(logger)
	httpServer := NewHTTPServer(logger, env, router)
	return httpServer, nil
}

// container.go:

var Container = wire.NewSet(
	NewEnv,
	NewLogger,
	NewRouter,
	NewHTTPServer, wire.Bind(new(http.Handler), new(mux.Router)))
