version: '3.0'

services:
    mysql:
        image: mysql:8.0
        volumes:
            - data:/var/lib/mysql
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: example
            MYSQL_DATABASE: test
            MYSQL_USER: user
            MYSQL_PASSWORD: password

    adminer:
        image: adminer
        ports:
            - 8080:8080

volumes:
    data:
