# This yaml is equivalent to the following command
# kubectl run hello-world --image=gcr.io/google-samples/node-hello:1.0  --port=8080
apiVersion: v1
kind: Pod
metadata:
    name: hello-world
spec:
    containers:
        - image: gcr.io/google-samples/node-hello:1.0
          name: hello-world
          ports:
              - containerPort: 8080
                name: http
                protocol: TCP
