apiVersion: v1
kind: Pod
metadata:
    name: hello-world
spec:
    containers:
        - image: gcr.io/google-samples/node-hello:1.0
          name: hello-world
          livenessProbe:
              httpGet:
                  path: /
                  port: 8080
              initialDelaySeconds: 5
              timeoutSeconds: 1
              periodSeconds: 10
              failureThreshold: 3
          ports:
              - containerPort: 8080
                name: http
                protocol: TCP
