cover:
	vendor/bin/phpunit --coverage-php coverage/SampleTest.cov tests/SampleTest.php
	vendor/bin/phpunit --coverage-php coverage/Sample2Test.cov tests/Sample2Test.php
	vendor/bin/phpcov merge coverage --html report
