// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protos/struct.proto

package protos

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _struct "github.com/golang/protobuf/ptypes/struct"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Sample struct {
	Fields               []*_struct.Struct `protobuf:"bytes,1,rep,name=fields" json:"fields,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Sample) Reset()         { *m = Sample{} }
func (m *Sample) String() string { return proto.CompactTextString(m) }
func (*Sample) ProtoMessage()    {}
func (*Sample) Descriptor() ([]byte, []int) {
	return fileDescriptor_struct_5a0f6dabe638834a, []int{0}
}
func (m *Sample) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Sample.Unmarshal(m, b)
}
func (m *Sample) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Sample.Marshal(b, m, deterministic)
}
func (dst *Sample) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Sample.Merge(dst, src)
}
func (m *Sample) XXX_Size() int {
	return xxx_messageInfo_Sample.Size(m)
}
func (m *Sample) XXX_DiscardUnknown() {
	xxx_messageInfo_Sample.DiscardUnknown(m)
}

var xxx_messageInfo_Sample proto.InternalMessageInfo

func (m *Sample) GetFields() []*_struct.Struct {
	if m != nil {
		return m.Fields
	}
	return nil
}

func init() {
	proto.RegisterType((*Sample)(nil), "protos.Sample")
}

func init() { proto.RegisterFile("protos/struct.proto", fileDescriptor_struct_5a0f6dabe638834a) }

var fileDescriptor_struct_5a0f6dabe638834a = []byte{
	// 107 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2e, 0x28, 0xca, 0x2f,
	0xc9, 0x2f, 0xd6, 0x2f, 0x2e, 0x29, 0x2a, 0x4d, 0x2e, 0xd1, 0x03, 0xf3, 0x84, 0xd8, 0x20, 0x82,
	0x52, 0x32, 0xe9, 0xf9, 0xf9, 0xe9, 0x39, 0xa9, 0xfa, 0x60, 0x6e, 0x52, 0x69, 0x1a, 0x8a, 0x2a,
	0x25, 0x4b, 0x2e, 0xb6, 0xe0, 0xc4, 0xdc, 0x82, 0x9c, 0x54, 0x21, 0x7d, 0x2e, 0xb6, 0xb4, 0xcc,
	0xd4, 0x9c, 0x94, 0x62, 0x09, 0x46, 0x05, 0x66, 0x0d, 0x6e, 0x23, 0x71, 0x3d, 0x88, 0x46, 0x3d,
	0x98, 0x46, 0xbd, 0x60, 0xb0, 0xc6, 0x20, 0xa8, 0xb2, 0x24, 0x88, 0x05, 0xc6, 0x80, 0x00, 0x00,
	0x00, 0xff, 0xff, 0xb0, 0xa1, 0x73, 0x8b, 0x7e, 0x00, 0x00, 0x00,
}
